# Generated by Django 3.0.4 on 2021-03-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210226_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ship_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_methods',
            field=models.BooleanField(default=False),
        ),
    ]
