# Generated by Django 3.0.4 on 2021-03-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210314_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(choices=[('option1', 'Standard'), ('option2', 'Express'), ('option3', 'Rush')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.CharField(choices=[('option1', 'Standard'), ('option2', 'Express'), ('option3', 'Rush')], default='Standard', max_length=20),
        ),
    ]
