# Generated by Django 3.0.4 on 2021-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210314_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ship_window',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_methods',
        ),
        migrations.AddField(
            model_name='order',
            name='ship_window',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_methods',
            field=models.BooleanField(default=False),
        ),
    ]
